config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  resources :sessions
  resources :users
  get 'welcome/index'

  resources :articles do
    resources :comments
    collection do
      get :search
    end
  end
  resources :subscribers
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
            length: {minimum: 3}
  validates :text, presence: true,
            length: {minimum: 2}
  def self.search(params)
      articles = Article.where("text LIKE ? or title LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
      articles
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :f_name, :l_name, :email, :country,
            presence: true


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||=User.find_by_id(session[:user_id]) if session[:user_id]
  end

  # ヘルパーメソッドの呼び出し
  helper_method :current_user
  # サインインしていない場合
  def authorize
    redirect_to new_session_path, alert: 'サインインもしくはユーザー登録して下さい。' if current_user.nil?
  end
  # 一般ユーザーの場合
  def admin_authorize
    redirect_to new_session_path,
    alert: "Only for Admin!" unless current_user.admin
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

# index, show, search以外は一般ユーザーでアクセスできない
before_action :admin_authorize, :except => [:index, :show, :search]

  # 記事一覧
  def index
    @articles = Article.all
  end

  # 新規記事作成
  def new
    @article = Article.new
  end

  # 記事詳細
  def show
    @article = Article.find(params[:id])
  end

  # 記事編集
  def edit
    @article = Article.find(params[:id])
  end

  # 記事検索
  def search
    if params[:search].blank?
      @articles = Article.all
    else
      @articles = Article.search(params)
    end
  end

  # 記事更新
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  # 記事投稿
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end

  # 記事削除
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

# タイトルと記事の中身の値をプライベートにセット
private
  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :authorize, :only => [:create]
before_action :admin_authorize, :only => [:destroy]

  def create
    @article = Article.find_by(params[:article_id])
    @comment = @article.comments.create(comment_params)
    if @comment.save
      redirect_to article_path(@article), notice: "コメントを投稿しました"
    else
      redirect_to article_path(@article), alert: "コメントを投稿できませんでした。"
    end
  end

  def destroy
    @article = Article.find_by(params[:article_id])
    @comment = @article.comments.find_by(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  # フォーム値の受け取り
  def create
    user = User.find_by_userid(params[:userid])
    if user && user.authenticate(params[:password])
      # ユーザーをサインインさせ、root_pathにリダイレクトさせる。
      session[:user_id] = user.id
      redirect_to root_path, notice:
      " #{user.userid}様、サインインに成功しました。"
    else
      # エラーメッセージを表示し、サインイン画面に戻る
      render 'new', alert:
      "ユーザーID  か パスワードが無効です。"
    end
  end

  # ログアウト
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice:
    "ログアウトに成功しました。"
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController


  def index
    @subscribers = Subscriber.all
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)
    if Subscriber.exists?(email: @subscriber.email)
      redirect_to root_path, alert:
      "こちらのメールアドレスは既に登録されています"
    elsif
      @subscriber.save
      redirect_to root_path, notice:
      " #{@subscriber.f_name}様、購読ありがとうございます。 "
    else
      redirect_to root_path, alert:
      "登録に失敗しました。もう一度登録をお願いします。"
    end
  end

def destroy
  @subscriber = Subscriber.find(params[:id])
  @subscriber.destroy

  redirect_to subscribers_path
end

  private
    def subscriber_params
      params.require(:subscriber).permit(:f_name, :l_name, :email, :country)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to articles_path, notice:
      " #{@user.userid}様ようこそ! ユーザー作成が完了しました。"
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:userid, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_link_to (nav_link, control, action, url, style)
    if controller_name == control && action_name == action
      return link_to nav_link, url, id: style
    else
      return link_to nav_link, url, class: style
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<div class="row" style="padding-top:10%">
  <div class="col"></div>
  <div class="col-md-7">
    <h1>記事編集</h1>
    <%= form_for @article do |f| %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text, class: 'form-control' %>
    </p>
    <p>
      <%= f.submit class: 'btn btn-lg btn-btn-success' %>
    </p>
  <% end %>

  <p>
    <%= link_to 'Back', articles_path, class: 'btn btn-md btn-info' %>
    <%= link_to 'Home', welcome_index_path, class: 'btn btn-md btn-primary' %>
  </p>
</div>
<div class="col"></div>
</div>

app/views/articles/index.html.erb
<div class="row">
  <div class="col"></div>
  <div class="col-md-10">
    <h1>記事リスト</h1>
    <% if current_user && current_user.admin? %>
    <p>
      <%= link_to '新規記事作成', new_article_path, class:'btn btn-lg btn-info' %>
    </p>
    <% end %>
    <table class="table table-hover table-striped table-responsive-xs table-info">
      <thead>
        <tr>
          <th>Title</th>
          <th>Text</th>
        <% if current_user && current_user.admin? %>
          <th colspan="3">編集オプション</th>
        <% else %>
          <th colspan="1">記事詳細</th>
        <% end %>
        </tr>
      </thead>
      <tbody>
        <% @articles.each do |article| %>
          <tr>
            <td>
              <%= article.title %>
            </td>
            <td>
              <%= truncate(article.text, length: 75) %>
            </td>
            <td>
              <%= link_to 'SHOW', article_path(article), class: 'btn btn-sm btn-info' %>
            </td>
              <% if current_user && current_user.admin? %>
            <td>
              <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-sm btn-warning' %>
            </td>
            <td>
              <%= link_to 'Delete',article_path(article), class: 'btn btn-sm btn-danger', method: :Delete, data: {confirm: '本当に削除しますか ?'} %>
            </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <p>
      <%= link_to 'Home', welcome_index_path, class: 'btn btn-sm btn-info' %>
    </p>
  </div>
  <div class="col"></div>
</div>

app/views/articles/new.html.erb
<div class="row" style="padding-top:0%">
  <div class="col"></div>
  <div class="col-md-4">
    <h3>新規記事作成</h3>
    <%= form_for :article, url: articles_path do |f| %>

    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@article.errors.count, "error") %>
          この記事は保存できません。
        </h2>

        <p>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
              <li>
                <%= msg %>
              </li>
              </ul>
          <% end %>
        </p>
        <% if alert %>
          <%= alert %>
        <% end %>
      </div>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text, class: 'form-control' %>
    </p>
    <p>
      <%= f.submit class: 'btn btn-lg btn-success' %>
    </p>
  <% end %>

  <p>
    <%= link_to 'Back', articles_path, class: 'btn btn-md btn-info' %>
    <%= link_to 'Home', welcome_index_path, class: 'btn btn-md btn-primary' %>
  </p>
  </div>
<div class="col"></div>
</div>

app/views/articles/search.html.erb
<div class="row">
  <div class="col"></div>
  <div class="col-md-10">
    <h1>検索記事リスト</h1>
    <table class="table table-hover table-striped table-responsive-xs table-info">
      <thead>
        <tr>
          <th>Title</th>
          <th>Text</th>
        <% if current_user && current_user.admin? %>
          <th colspan="3">編集オプション</th>
        <% else %>
          <th colspan="1">記事詳細</th>
        <% end %>
        </tr>
      </thead>
      <tbody>
        <% @articles.each do |article| %>
          <tr>
            <td>
              <%= article.title %>
            </td>
            <td>
              <%= truncate(article.text, length: 75) %>
            </td>
            <td>
              <%= link_to 'SHOW', article_path(article), class: 'btn btn-sm btn-info' %>
            </td>
            <% if current_user && current_user.admin? %>
            <td>
              <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-sm btn-warning' %>
            </td>
            <td>
              <%= link_to 'Delete',article_path(article), class: 'btn btn-sm btn-danger', method: :Delete, data: {confirm: '本当に削除しますか ?'} %>
            </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <p>
      <%= link_to '記事一覧に戻る', articles_path, class: 'btn btn-sm btn-info' %>
    </p>
  </div>
  <div class="col"></div>
</div>

app/views/articles/show.html.erb
<div class="row">
  <div class="col"></div>
  <div class="col-md-7">
    <%= image_tag 'nobuo_blog.jpg', :class => "style_image2" %>
    <p>
      <h2>タイトル</h2>
      <strong><%= @article.title %></strong>
    </p>
    <p>
      <%= @article.created_at.strftime('%A %-b %-d, %Y | %l:%M %p') %>
    </p>
    <p>
      <h3>記事</h3>
      <%= @article.text %>
    </p>
    <hr>

    <%= render 'comments/comment' %>

    <% if current_user %>
    <hr>

    <%= render 'comments/form' %>
    <% else %>
    <%= link_to 'サインイン', new_session_path %> か <%= link_to 'ユーザー登録', new_user_path %>をして下さい。
    <% end %>

    <p><br><%= link_to 'Back', articles_path, class: 'btn btn-md btn-info' %>
      <%= link_to 'Home', welcome_index_path, class: 'btn btn-md btn-primary' %>
    </p>
  </div>
  <div class="col"></div>
</div>

app/views/comments/_comment.html.erb
<h2>コメント一覧</h2>
<% @article.comments.each do |comment| %>
  <p>
    <strong>名前</strong>
    <%= comment.commenter %>
  </p>
  <p>
    <%= comment.created_at %>
  </p>
  <p>
    <strong>コメント</strong>
    <%= comment.body %>
  </p>
  <% if current_user && current_user.admin? %>
    <p>
      <%= link_to 'コメント削除', [comment.article, comment], class: 'btn btn-md btn-danger', method: :Delete, data: {confirm: '本当に削除しますか?'} %>
    </p>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<h4> コメント追加 </h4>
<%= form_for([@article, @article.comments.build]) do |f| %>
<div class="field" style="100%;" >
<p>
  <%= f.label :commenter %><br>
  <%= f.text_field :commenter, class: 'form-control' %>
</p>
<p>
  <%= f.label :body %><br>
  <%= f.text_area :body, class: 'form-control' %>
</p>
<p>
  <%= f.submit class: 'btn btn-lg btn-success' %>
</p>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <div class="container">
      <% if notice %>
        <div class="show_notice">
          <%= notice %>
        </div>
      <% end %>

      <% if alert %>
        <div class="show_alert">
          <%= alert %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<section class="footer">
  <div class="row">
    <div class="col-md-4 darker">
      <div class="col-md-12 pd white">
        <h4>General Info</h4>
        <hr>
        <h5 class="linktxt">Address Line1</h5>
        <h5 class="linktxt">Address Line2</h5>
        <h5 class="linktxt">Address Line3</h5>
        <hr>
        <p class="small-font gray">&copy; nobuo_web 2019 All Rights Rserved</p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="col-md-12 pd white">
        <h4>Subscribe</h4>
        <hr>

        <%= form_for :subscriber, url: subscribers_path do |f| %>
        <%= f.text_field :f_name, placeholder: "First Name",
                        class:"form-control mr-sm-2 sm_style" %>
        <%= f.text_field :l_name, placeholder: "Last Name",
                        class:"form-control mr-sm-2 sm_style" %>
        <%= f.email_field :email, placeholder: "Your Email",
                        class:"form-control mr-sm-2 sm_style" %>
        <div class="form-control2 sm_style" >
        <%= f.select :country,
              options_for_select(['東京', '大阪', '福岡', '北海道']),
              prompt: '都道府県' %>
        </div>
        <%= f.submit '送信', class:"btn btn-light my-2 my-sm-0" %>
        <% end %>
      </div>
    </div>
    <div class="col-md-4 dark">
      <div class="col-md-12 pd white">
        <h4>SNS</h4>
        <h5><%= link_to 'facebook', 'https://www.facebook.com/igarashi.nobuo', class:"linktxt" %></h5>
        <h5><%= link_to 'twitter', 'https://twitter.com/nobuoaida', class:"linktxt" %></h5>
        <h5><%= link_to 'youtube', 'https://www.youtube.com/channel/UCeJJmI6Vpk9qvR81jzVngGQ', class:"linktxt" %></h5>
      </div>
    </div>
  </div>
</section>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Nobuo's Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div id="navbarCollapse" class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= active_link_to 'ホーム','welcome', 'index', welcome_index_path, "active_nav-link" %>
      </li>
      <li class="nav-item">
        <%= active_link_to 'ブログ', 'articles', 'index', articles_path, "active_nav-link" %>
      </li>
      <% if current_user && current_user.admin? %>
        <li class="nav-link">
          <%= active_link_to '購読者一覧', 'subscribers','index', subscribers_path, class:"active_nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'サインアウト', session_path('active'), method: :delete, class:"active_nav-link"%>
        </li>
        <li class="nav-link">
          <%= current_user.userid %>様
        </li>
      <% elsif current_user %>
        <li class="nav-item">
          <%= link_to 'サインアウト', session_path('active'), method: :delete, class: "active_nav-link"%>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'サインイン', new_session_path, class: "active_nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'ユーザー作成', new_user_path, class: "active_nav-link" %>
        </li>
      <% end %>
      </ul>


      <div class="form-inline mt-2 mt-md-0">
        <%= form_tag search_articles_path, method: :get do %>
        <%= text_field_tag :search, nil, placeholder: "Search", class: "form-control mr-sm-2" %>
        <%= submit_tag "Search", class: "btn btn-light my-2 my-sm-0" %>
      <% end %>
    </div>
  </div>
</nav>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

app/views/subscribers/index.html.erb
<div class="row">
  <div class="col"></div>
  <div class="col-md-10">
    <h1>購読者リスト</h1>
    <p>
      <%= link_to '新規記事作成', new_article_path, class:'btn btn-lg btn-info' %>
    </p>

    <table class="table table-hover table-striped table-responsive-xs table-info">
      <thead>
        <tr>
          <th>氏</th>
          <th>名</th>
          <th>メールアドレス</th>
          <th>国</th>
          <th>削除</th>
        </tr>
      </thead>
      <tbody>
        <% @subscribers.each do |subscriber| %>
          <tr>
            <td>
              <%= subscriber.f_name %>
            </td>
            <td>
              <%= subscriber.l_name %>
            </td>
            <td>
              <%= subscriber.email %>
            </td>
            <td>
              <%= subscriber.country %>
            </td>
            <td>
              <%= link_to 'Delete',subscriber_path(subscriber), class: 'btn btn-sm btn-danger', method: :Delete, data: {confirm: '本当に削除しますか ?'} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <p>
      <%= link_to 'Home', welcome_index_path, class: 'btn btn-sm btn-info' %>
    </p>
  </div>
  <div class="col"></div>
</div>

app/views/users/index.html.erb
<h1> views/users/index </h1>

app/views/users/new.html.erb
<div class="row" style="padding-top:10%">
  <div class="col"></div>
  <div class="col-md-7">
    <h1>ユーザー登録</h1>
    <%= form_for @user do |f| %>
    <div class="field" style="100%;">
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@user.errors.count, "error") %>
            ユーザー登録に失敗しました。
          </h2>
          <p>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li>
                  <%= msg %>
                </li>
              <% end %>
            </ul>
          </p>
          <% if alert %>
            <%= alert %>
          <% end %>
        </div>
      <% end %>
      <%= f.text_field :userid, placeholder: 'ID', class: 'form-control' %><br>
      <%= f.email_field :email, placeholder: 'email', class: 'form-control' %><br>
      <%= f.password_field :password, placeholder: 'パスワード', class: 'form-control' %><br>
      <%= f.password_field :password_confirmation, placeholder: 'パスワードを確認して下さい。', class: 'form-control' %><br>
      <%= f.submit 'アカウント作成',  class:"btn btn-light my-2 my-sm-0"%>
    <% end %>
  </div>
  <p>
    <br><%= link_to '記事一覧', articles_path, class: 'btn btn-md btn-info' %>
    <%= link_to 'Home', welcome_index_path, class: 'btn btn-md btn-primary' %>
  </p>
</div>
<div class="col"></div>
</div>

app/views/welcome/index.html.erb
<div class="row" style="padding-top:6%">
  <div class="col"></div>
  <div class="col-md-7 text-center">
    <%= image_tag 'nobuo_blog.jpg', :class => "style_image" %>
    <div class="jumbotron">
      <h1>Welcome to Nobuo's Blog</h1>
      <p><%= link_to 'Read my Blog', articles_path, class: 'btn btn-lg btn-welcome' %></p>
    </div>
  </div>
  <div class="col"></div>
</div>